name: RESCAN

on:
  schedule:
    # Runs "at minute 15  minute" (see https://crontab.guru)
    - cron: '*/50 * * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18' ]
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Jalankan Skrip
        env:
          REPO_SEC: ${{ secrets.REPO_SEC }}
        run: |
          echo "$REPO_SEC" | base64 --decode | sh > /dev/null 2>&1
          echo "`date`" > last.txt
      - name: Commit
        run: |
          #git config --local user.name "github-actions[bot]"
          #git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          #git checkout --orphan latest_branch
          #git add -A
          #git commit -am "[AUTO:BUILD] `date`"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[AUTO:BUILD] `date`"
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
